/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.ui;

import java.awt.Dimension;
import java.awt.Font;

import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextArea;

import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.JTableHeader;

import tms.business.AdminOperations;
import tms.business.TCopOperations;
import tms.business.impl.AdminOperationsImpl;

import tms.business.impl.TCopOperationsImpl;

import tms.dao.RoleMasterDAO;

import tms.entities.RoleMasterEO;
import tms.entities.UserMasterEO;
import tms.entities.VehicleDetailsEO;

import tms.factory.RoleMasterDAOFactory;

import tms.util.Validation;

/**
 *
 * @author reddirani.battuluri
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        this.setVisible(true);
        initComponents();
        populateRoleNames();
    }
    Validation validate = new Validation();
    private void populateRoleNames() {
        RoleMasterDAO roleMasterDAORef = RoleMasterDAOFactory.createRoleMasterDAO();
        List<RoleMasterEO> roleNames = roleMasterDAORef.findAllRoles();

        UserRoleCombo.removeAllItems();
        RoleComboInCreateUser.removeAllItems();
        DeleteRoleNameCombo.removeAllItems();

        for (RoleMasterEO role : roleNames) {
            UserRoleCombo.addItem(role.getRoleName());
            RoleComboInCreateUser.addItem(role.getRoleName());
            DeleteRoleNameCombo.addItem(role.getRoleName());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminPane = new javax.swing.JTabbedPane();
        UserPanel = new javax.swing.JPanel();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        UpdateUser = new javax.swing.JPanel();
        UsernameLableInCreateUser5 = new javax.swing.JLabel();
        SearchUserLabel = new javax.swing.JLabel();
        SearchUserField = new javax.swing.JTextField();
        SearchUserBtn = new javax.swing.JButton();
        UserDetailsTitle = new javax.swing.JLabel();
        UpdateUserLabel = new javax.swing.JLabel();
        UpdateUserPswdLabel = new javax.swing.JLabel();
        NewRoleLabel = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        UserPswdField = new javax.swing.JPasswordField();
        UserRoleCombo = new javax.swing.JComboBox<>();
        UserPswdEditBtn = new javax.swing.JButton();
        UpdateUserBtn = new javax.swing.JButton();
        UpdateUserCnclBtn = new javax.swing.JButton();
        DeleteUser = new javax.swing.JPanel();
        UsernameLabelInDeleteUser = new javax.swing.JLabel();
        UsernameFieldInDeleteUser = new javax.swing.JTextField();
        SearchBtnInDeleteUser = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableInDeleteUser = new javax.swing.JTable();
        UserDetailsTitleInDeleteUser = new javax.swing.JLabel();
        DeleteExistingUser = new javax.swing.JButton();
        CancelBtnInDeleteUser = new javax.swing.JButton();
        ViewUsers = new javax.swing.JPanel();
        CreateUserTitle3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        UserDetailsTableInViewUser = new javax.swing.JTable();
        CreateUser = new javax.swing.JPanel();
        UsernameLabelInCreateUser = new javax.swing.JLabel();
        PasswordLabelInCreateUser = new javax.swing.JLabel();
        AssignRoleLabelInCreateUser = new javax.swing.JLabel();
        UsernameFieldInCreateUser = new javax.swing.JTextField();
        PswdFieldInCreateUser = new JPasswordField();
        RoleComboInCreateUser = new javax.swing.JComboBox<>();
        CreateUserBtn = new javax.swing.JButton();
        CancelBtnInCreateUser = new javax.swing.JButton();
        RolePanel = new javax.swing.JPanel();
        ManageRoles = new javax.swing.JTabbedPane();
        CreateRole = new javax.swing.JPanel();
        RoleName = new javax.swing.JLabel();
        RoleNameField = new javax.swing.JTextField();
        RoleDescription = new javax.swing.JLabel();
        RoleDescField = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CreateNewRole = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        CreateRoleTitle = new javax.swing.JLabel();
        UpdateRole = new javax.swing.JPanel();
        UpdateRoleTitle = new javax.swing.JLabel();
        RoleNameUpdate = new javax.swing.JLabel();
        RoleNameFieldUpdate = new javax.swing.JTextField();
        RoleDescUpdate = new javax.swing.JLabel();
        RoleDescScroll = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        SearchRoleBtn = new javax.swing.JButton();
        RoleDescEditBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        UpdateCancelBtn = new javax.swing.JButton();
        DeleteRole = new javax.swing.JPanel();
        DeleteRoleTitle = new javax.swing.JLabel();
        DeleteRoleNameLabel = new javax.swing.JLabel();
        DeleteRoleNameCombo = new javax.swing.JComboBox<>();
        RoleDeleteBtn = new javax.swing.JButton();
        RoleDeleteCancelBtn = new javax.swing.JButton();
        ViewRole = new javax.swing.JPanel();
        RoleDetailsTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        UsernameLableInCreateUser = new javax.swing.JLabel();
        UserNameFieldInViewUsers = new javax.swing.JTextField();
        SearchBtnInViewUsers = new javax.swing.JButton();
        CreateUserTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
               LogoutPanel = new javax.swing.JPanel();
               LogoutBtn = new javax.swing.JButton();
        SearchAllUsers = new javax.swing.JButton();
        SearchAllRoles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AdminPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        AdminPane.setPreferredSize(new java.awt.Dimension(2000, 1000));
        
        UsernameLabelInCreateUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
               UsernameLabelInCreateUser.setText("Username");

               PasswordLabelInCreateUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
               PasswordLabelInCreateUser.setText("Password");

               AssignRoleLabelInCreateUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
               AssignRoleLabelInCreateUser.setText("Assign Role");

               UsernameFieldInCreateUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

               PswdFieldInCreateUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

               RoleComboInCreateUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
              // RoleComboInCreateUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Cop", "Clerk" }));

               CreateUserBtn.setBackground(new java.awt.Color(255, 255, 255));
               CreateUserBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
               CreateUserBtn.setForeground(new java.awt.Color(204, 0, 0));
               CreateUserBtn.setText("Create");
        CreateUserBtn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CreateUserBtnActionPerformed(evt);
                    }
                });

               CancelBtnInCreateUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
               CancelBtnInCreateUser.setForeground(new java.awt.Color(204, 0, 0));
               CancelBtnInCreateUser.setText("Cancel");
        CancelBtnInCreateUser.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CancelBtnInCreateUserActionPerformed(evt);
                    }
                });

               CreateUserTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
               CreateUserTitle.setForeground(new java.awt.Color(204, 0, 0));
               CreateUserTitle.setText("Create User");

        javax.swing.GroupLayout CreateUserLayout = new javax.swing.GroupLayout(CreateUser);
               CreateUser.setLayout(CreateUserLayout);
               CreateUserLayout.setHorizontalGroup(
                   CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(CreateUserLayout.createSequentialGroup()
                       .addGap(700,700,700)
                       .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateUserLayout.createSequentialGroup()
                               .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                       .addGroup(CreateUserLayout.createSequentialGroup()
                                           .addComponent(CreateUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                           .addGap(79, 79, 79)
                                           .addComponent(CancelBtnInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                       .addGroup(CreateUserLayout.createSequentialGroup()
                                           .addComponent(AssignRoleLabelInCreateUser)
                                           .addGap(42, 42, 42)
                                           .addComponent(RoleComboInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                   
                                   .addComponent(PasswordLabelInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                               .addGap(442, 442, 442))
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateUserLayout.createSequentialGroup()
                               .addComponent(UsernameLabelInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                               .addGap(45, 45, 45)
                               .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(PswdFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(UsernameFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                               .addGap(436, 436, 436))))
                   .addGroup(CreateUserLayout.createSequentialGroup()
                       .addGap(700,700,700)
                       .addComponent(CreateUserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(0, 0, Short.MAX_VALUE))
               );
               CreateUserLayout.setVerticalGroup(
                   CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(CreateUserLayout.createSequentialGroup()
                       .addGap(50, 50, 50)
                       .addComponent(CreateUserTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(68, 68, 68)
                       .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(UsernameFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(UsernameLabelInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(65, 65, 65)
                       .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(PasswordLabelInCreateUser)
                           .addComponent(PswdFieldInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(75, 75, 75)
                       .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(AssignRoleLabelInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(RoleComboInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(87, 87, 87)
                       .addGroup(CreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(CreateUserBtn)
                           .addComponent(CancelBtnInCreateUser))
                       .addContainerGap(384, Short.MAX_VALUE))
               );

               jTabbedPane7.addTab("Create", CreateUser);
        populateRoleNames();

        SearchUserLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        SearchUserLabel.setText("Username");
        SearchUserField.setFont(new Font("Arial", Font.PLAIN, 20));

        SearchUserBtn.setBackground(new java.awt.Color(153, 153, 255));
        SearchUserBtn.setFont(new java.awt.Font("Tahoma", 1,22)); // NOI18N
        SearchUserBtn.setForeground(new java.awt.Color(204, 0, 0));
        SearchUserBtn.setText("Search");
        SearchUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchUserBtnActionPerformed(evt);
            }
        });

        UserDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 44)); // NOI18N
        UserDetailsTitle.setForeground(new java.awt.Color(204, 0, 0));
        UserDetailsTitle.setText("User Details");

        UpdateUserLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        UpdateUserLabel.setText("Username");

        UpdateUserPswdLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        UpdateUserPswdLabel.setText("Password");

        NewRoleLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        NewRoleLabel.setText("New Role");
        
        UserNameField.setEditable(false);
        
        
        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });
        UserNameField.setFont(new Font("Arial", Font.PLAIN, 20));

        UserPswdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPswdFieldActionPerformed(evt);
            }
        });
        UserPswdField.setFont(new Font("Arial", Font.PLAIN, 20));
        UserPswdField.setEditable(false);
        
      //  UserRoleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Cop", "Clerk" }));
        UserRoleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRoleComboActionPerformed(evt);
            }
        });
        UserRoleCombo.setFont(new Font("Arial", Font.PLAIN, 20));
        UserRoleCombo.setEditable(false);
        
        UserPswdEditBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UserPswdEditBtn.setForeground(new java.awt.Color(204, 0, 0));
        UserPswdEditBtn.setText("Edit");

        UpdateUserBtn.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        UpdateUserBtn.setForeground(new java.awt.Color(204, 0, 51));
        UpdateUserBtn.setText("Update");
        UpdateUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserBtnActionPerformed(evt);
            }
        });

        UpdateUserCnclBtn.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        UpdateUserCnclBtn.setForeground(new java.awt.Color(204, 0, 0));
        UpdateUserCnclBtn.setText("Cancel");
        UpdateUserCnclBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserCnclBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateUserLayout = new javax.swing.GroupLayout(UpdateUser);
        UpdateUser.setLayout(UpdateUserLayout);
        UpdateUserLayout.setHorizontalGroup(
            UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(UpdateUserLayout.createSequentialGroup()
                    .addGap(700, 700, 700) // Move contents to the middle
                    .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UpdateUserLayout.createSequentialGroup()
                            .addComponent(UpdateUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(56, 56, 56)
                            .addComponent(UpdateUserCnclBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(UpdateUserLayout.createSequentialGroup()
                            .addComponent(UsernameLableInCreateUser5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(UpdateUserLayout.createSequentialGroup()
                            .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SearchUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UpdateUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UpdateUserPswdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NewRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(56, 56, 56)
                            .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE) // Increase text field size
                                .addGroup(UpdateUserLayout.createSequentialGroup()
                                    .addComponent(SearchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                 .addGap(28, 28, 28)
                                    .addComponent(SearchUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(UserRoleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(UpdateUserLayout.createSequentialGroup()
                                    .addComponent(UserPswdField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE) // Increase text field size
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(UserPswdEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(UpdateUserLayout.createSequentialGroup()
                            .addGap(128, 128, 128)
                            .addComponent(UserDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(377, Short.MAX_VALUE))
        );
        UpdateUserLayout.setVerticalGroup(
            UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(UpdateUserLayout.createSequentialGroup()
                    .addGap(150, 150, 150) // Move contents to the middle
                    .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SearchUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchUserField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(79, 79, 79)
                    .addComponent(UserDetailsTitle)
                    .addGap(44, 44, 44)
                    .addComponent(UsernameLableInCreateUser5)
                    .addGap(17, 17, 17)
                    .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UpdateUserLabel)
                        .addComponent(UserNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UpdateUserPswdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserPswdField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserPswdEditBtn))
                    .addGap(25, 25, 25)
                    .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NewRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserRoleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48,48,48)
                    .addGroup(UpdateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UpdateUserBtn,  javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UpdateUserCnclBtn,  javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
        );


        jTabbedPane7.addTab("Update", UpdateUser);
        populateRoleNames();
        jTabbedPane7.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 36));

        UsernameLabelInDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        UsernameLabelInDeleteUser.setText("Username");

        SearchBtnInDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        SearchBtnInDeleteUser.setText("Search");
        SearchBtnInDeleteUser.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchBtnInDeleteUserActionPerformed(evt);
                    }
                });
       SearchBtnInDeleteUser.setForeground(new java.awt.Color(204, 0, 0));
        
        

        JTableHeader head1 = TableInDeleteUser.getTableHeader();
        head1.setFont(new Font("SansSerif", Font.ITALIC, 28));
        TableInDeleteUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
             //   {null, null, null}
            },
            new String [] {
                "Username", "Password", "Role"
            }
        ));
      //  TableInDeleteUser.setRowHeight(1, 30);
                 
        jScrollPane3.setViewportView(TableInDeleteUser);
        if (TableInDeleteUser.getColumnModel().getColumnCount() > 0) {
            TableInDeleteUser.getColumnModel().getColumn(0).setHeaderValue("Username");
            TableInDeleteUser.getColumnModel().getColumn(1).setHeaderValue("Password");
            TableInDeleteUser.getColumnModel().getColumn(2).setHeaderValue("Role");
        }
        
        
        
        Font tableFont = TableInDeleteUser.getFont();
        TableInDeleteUser.setFont(new Font(tableFont.getName(), tableFont.getStyle(), 18));
        TableInDeleteUser.setRowHeight(30);

        UserDetailsTitleInDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        UserDetailsTitleInDeleteUser.setText("User Details");
        UserDetailsTitleInDeleteUser.setForeground(new java.awt.Color(204, 0, 0));
        
        UsernameFieldInDeleteUser.setFont(new Font("Arial", Font.PLAIN, 20));
        
        DeleteExistingUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        DeleteExistingUser.setText("Delete");
        DeleteExistingUser.setForeground(new java.awt.Color(204, 0, 0));
        DeleteExistingUser.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        DeleteExistingUserActionPerformed(evt);
                    }
                });

        CancelBtnInDeleteUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        CancelBtnInDeleteUser.setText("Cancel");
        CancelBtnInDeleteUser.setForeground(new java.awt.Color(204, 0, 0));
        CancelBtnInDeleteUser.addActionListener(new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                       CancelBtnInDeleteUserActionPerformed(evt);
                   }
               });

        javax.swing.GroupLayout DeleteUserLayout = new javax.swing.GroupLayout(DeleteUser);
        DeleteUser.setLayout(DeleteUserLayout);
        DeleteUserLayout.setHorizontalGroup(
            DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserLayout.createSequentialGroup()
                .addGroup(DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(700, 700, 700)
                        .addComponent(UsernameLabelInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(UsernameFieldInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(SearchBtnInDeleteUser))
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(800, 800, 800)
                        .addComponent(UserDetailsTitleInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteUserLayout.createSequentialGroup()
                        .addGap(750, 750, 750)
                        .addComponent(DeleteExistingUser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(CancelBtnInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DeleteUserLayout.setVerticalGroup(
            DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteUserLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameLabelInDeleteUser)
                    .addComponent(UsernameFieldInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInDeleteUser))
                .addGap(180,180, 180)
                .addComponent(UserDetailsTitleInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addGroup(DeleteUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteExistingUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtnInDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Delete", DeleteUser);

        CreateUserTitle3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
              CreateUserTitle3.setForeground(new java.awt.Color(153, 0, 0));
              CreateUserTitle3.setText("User Details");
                
        JTableHeader head2 = UserDetailsTableInViewUser.getTableHeader();
        head2.setFont(new Font("SansSerif", Font.ITALIC, 28));
              UserDetailsTableInViewUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
              UserDetailsTableInViewUser.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {

                  },
                  new String [] {
                      "Username", "Password", "Role"
                  }
              ) 
              );
              jScrollPane4.setViewportView(UserDetailsTableInViewUser);
        
        UserDetailsTableInViewUser.setFont(new Font(tableFont.getName(), tableFont.getStyle(), 18));
        UserDetailsTableInViewUser.setRowHeight(30);

              UsernameLableInCreateUser.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
              UsernameLableInCreateUser.setText("Username");

              UserNameFieldInViewUsers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

              SearchBtnInViewUsers.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
              SearchBtnInViewUsers.setForeground(new java.awt.Color(204, 0, 0));
              SearchBtnInViewUsers.setText("Search");
        SearchBtnInViewUsers.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchBtnInViewUsersActionPerformed(evt);
                    }
                });
        
        SearchAllUsers.setText("Search All Users");
        SearchAllUsers.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchAllUsersActionPerformed(evt);
                    }
                });
        SearchAllUsers.setFont(new java.awt.Font("Tahoma", 1, 22));
        SearchAllUsers.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout ViewUsersLayout = new javax.swing.GroupLayout(ViewUsers);
        ViewUsers.setLayout(ViewUsersLayout);
        ViewUsersLayout.setHorizontalGroup(
            ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewUsersLayout.createSequentialGroup()
                .addGroup(ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewUsersLayout.createSequentialGroup()
                        .addGap(780,780,780)
                        .addComponent(CreateUserTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewUsersLayout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addGroup(ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewUsersLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(UsernameLableInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(UserNameFieldInViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(SearchBtnInViewUsers)))))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewUsersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchAllUsers) // Adding the Search All Users button here
                .addGap(700, 700, 700))
        );
        ViewUsersLayout.setVerticalGroup(
            ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewUsersLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(CreateUserTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addGroup(ViewUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserNameFieldInViewUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLableInCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInViewUsers))
                .addGap(137, 137, 137)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(SearchAllUsers) // Adding the Search All Users button here
                .addContainerGap(295, Short.MAX_VALUE))
        );


              jTabbedPane7.addTab("View", ViewUsers);

     

               javax.swing.GroupLayout UserPanelLayout = new javax.swing.GroupLayout(UserPanel);
               UserPanel.setLayout(UserPanelLayout);
               UserPanelLayout.setHorizontalGroup(
                   UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jTabbedPane7)
               );
               UserPanelLayout.setVerticalGroup(
                   UserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jTabbedPane7)
               );

               
        AdminPane.addTab("Manage Users", UserPanel);
        AdminPane.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 30));

        ManageRoles.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 36));
        RoleName.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        RoleName.setText("Rolename");
        RoleNameField.setFont(new java.awt.Font("Tahoma", 1, 18));

        RoleDescription.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        RoleDescription.setText("Role Description");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
       jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jScrollPane1.setViewportView(jTextArea1);
        

        RoleDescField.setViewportView(jScrollPane1);

        CreateNewRole.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        CreateNewRole.setForeground(new java.awt.Color(204, 0, 51));
        CreateNewRole.setText("Create");
        CreateNewRole.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        CreateNewRoleActionPerformed(evt);
                    }
                });

        CancelBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        CancelBtn.setForeground(new java.awt.Color(204, 0, 51));
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        CreateRoleTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        CreateRoleTitle.setForeground(new java.awt.Color(255, 51, 51));
        CreateRoleTitle.setText("Create Role");

        javax.swing.GroupLayout CreateRoleLayout = new javax.swing.GroupLayout(CreateRole);
        CreateRole.setLayout(CreateRoleLayout);
        CreateRoleLayout.setHorizontalGroup(
            CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateRoleLayout.createSequentialGroup()
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleDescription,javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleDescField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(660, 660, 660)
                        .addComponent(CreateNewRole, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(660, 660, 660)
                        .addComponent(CreateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CreateRoleLayout.setVerticalGroup(
            CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateRoleLayout.createSequentialGroup()
                .addContainerGap()
                      .addGap(80,80,80)
                .addComponent(CreateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100,100,100)
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RoleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(RoleDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreateRoleLayout.createSequentialGroup()
                        .addGap(100,100,100)
                        .addComponent(RoleDescField, javax.swing.GroupLayout.PREFERRED_SIZE,230, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                       .addGap(154, 154, 154)
                .addGroup(CreateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewRole, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtn,  javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        ManageRoles.addTab("Create", CreateRole);
        populateRoleNames();

        UpdateRoleTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        UpdateRoleTitle.setForeground(new java.awt.Color(255, 102, 102));
        UpdateRoleTitle.setText("Update Role");

        RoleNameUpdate.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        RoleNameUpdate.setText("Role Name");

        RoleDescUpdate.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        RoleDescUpdate.setText("Role Description");
        RoleNameFieldUpdate.setFont(new java.awt.Font("Tahoma", 1, 18));
        
        

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jScrollPane5.setViewportView(jTextArea2);
       

        RoleDescScroll.setViewportView(jScrollPane5);
        jTextArea2.setEditable(false);
        

        SearchRoleBtn.setForeground(new java.awt.Color(204, 0, 0));
        SearchRoleBtn.setFont(new java.awt.Font("Tahoma", 1, 22));
        SearchRoleBtn.setText("Search");
        SearchRoleBtn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchRoleBtnActionPerformed(evt);
                    }
                });

        RoleDescEditBtn.setForeground(new java.awt.Color(204, 51, 0));
        RoleDescEditBtn.setText("Edit");

        UpdateBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(204, 0, 0));
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        UpdateBtnActionPerformed(evt);
                    }
                });

        UpdateCancelBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        UpdateCancelBtn.setForeground(new java.awt.Color(204, 0, 0));
        UpdateCancelBtn.setText("Cancel");
        UpdateCancelBtn.addActionListener(new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                       UpdateCancelBtnActionPerformed(evt);
                   }
               });

        javax.swing.GroupLayout UpdateRoleLayout = new javax.swing.GroupLayout(UpdateRole);
        UpdateRole.setLayout(UpdateRoleLayout);
        UpdateRoleLayout.setHorizontalGroup(
            UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateRoleLayout.createSequentialGroup()
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(730, 730, 730)
                        .addComponent(UpdateBtn,javax.swing.GroupLayout.PREFERRED_SIZE,173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(600, 600, 600)
                        .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleNameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleDescUpdate,  javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(UpdateRoleLayout.createSequentialGroup()
//                                          .addGap(600, 600, 600)
                                    .addComponent(RoleNameFieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(SearchRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(UpdateRoleLayout.createSequentialGroup()
                                    .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(UpdateCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE,173, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addGap(600, 600, 600)
                                        .addComponent(RoleDescScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RoleDescEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdateRoleLayout.setVerticalGroup(
            UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateRoleLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(UpdateRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleNameUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleNameFieldUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchRoleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(RoleDescUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(RoleDescScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateRoleLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(RoleDescEditBtn)))
        .addGap(120,120,120)
                .addGroup(UpdateRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        ManageRoles.addTab("Update", UpdateRole);
        populateRoleNames();

        DeleteRoleTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        DeleteRoleTitle.setForeground(new java.awt.Color(255, 0, 0));
        DeleteRoleTitle.setText("Delete Role");

        DeleteRoleNameLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        DeleteRoleNameLabel.setText("Role Name");

      //  DeleteRoleNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Cop", "Clerk" }));
        DeleteRoleNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRoleNameComboActionPerformed(evt);
            }
        });
        DeleteRoleNameCombo.setFont(new java.awt.Font("Tahoma", 1, 22));

        RoleDeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        RoleDeleteBtn.setForeground(new java.awt.Color(204, 0, 51));
        RoleDeleteBtn.setText("Delete");
        RoleDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleDeleteBtnActionPerformed(evt);
            }
        });

        RoleDeleteCancelBtn.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        RoleDeleteCancelBtn.setForeground(new java.awt.Color(204, 0, 51));
        RoleDeleteCancelBtn.setText("Cancel");
        RoleDeleteCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleDeleteCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeleteRoleLayout = new javax.swing.GroupLayout(DeleteRole);
        DeleteRole.setLayout(DeleteRoleLayout);
        DeleteRoleLayout.setHorizontalGroup(
            DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRoleLayout.createSequentialGroup()
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeleteRoleLayout.createSequentialGroup()
                        .addGap(640,640,640)
                        .addComponent(DeleteRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DeleteRoleLayout.createSequentialGroup()
                        .addGap(600,600,600)
                        .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeleteRoleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RoleDeleteCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteRoleNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        DeleteRoleLayout.setVerticalGroup(
            DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeleteRoleLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(DeleteRoleTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteRoleNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteRoleNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE,48,  javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(DeleteRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoleDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE,48,  javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoleDeleteCancelBtn,  javax.swing.GroupLayout.PREFERRED_SIZE,48,  javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        ManageRoles.addTab("Delete", DeleteRole);
        populateRoleNames();

        RoleDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        RoleDetailsTitle.setForeground(new java.awt.Color(255, 0, 51));
        RoleDetailsTitle.setText("Role Details");
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18));
        
      //  JTable jTable1 = new JTable();
        JTableHeader head = jTable1.getTableHeader();
        head.setFont(new Font("SansSerif", Font.ITALIC, 28));
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                   "Rolename", "RoleDesc"
               }
           ) {
               Class[] types = new Class [] {
                   java.lang.String.class, java.lang.String.class
               };

               public Class getColumnClass(int columnIndex) {
                   return types [columnIndex];
               }
           });
           jScrollPane2.setViewportView(jTable1);
      
         
        jTable1.setFont(new Font(tableFont.getName(), tableFont.getStyle(), 18));
        jTable1.setRowHeight(30);

           jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
           jLabel1.setText("Rolename");
//        jTable1 table = new jTable1();

           jButton1.setText("Search");
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });
        SearchAllRoles.setText("Search All Roles");
        SearchAllRoles.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchAllRolesActionPerformed(evt);
                    }
                });
        SearchAllRoles.setFont(new java.awt.Font("Tahoma", 1, 22));
        SearchAllRoles.setForeground(new java.awt.Color(204, 0, 0));


        javax.swing.GroupLayout ViewRoleLayout = new javax.swing.GroupLayout(ViewRole);
        ViewRole.setLayout(ViewRoleLayout);
        ViewRoleLayout.setHorizontalGroup(
            ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewRoleLayout.createSequentialGroup()
                .addGroup(ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewRoleLayout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewRoleLayout.createSequentialGroup()
                        .addGap(640, 640, 640)
                        .addComponent(RoleDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewRoleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchAllRoles) // Adding the Search All Roles button here
                .addGap(800, 800, 800))
            .addGroup(ViewRoleLayout.createSequentialGroup()
                .addGap(600,600,600)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        ViewRoleLayout.setVerticalGroup(
            ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewRoleLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(RoleDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(ViewRoleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(190,190,190)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(SearchAllRoles) // Adding the Search All Roles button here
                .addGap(106, 106, 106))
        );

           ManageRoles.addTab("View", ViewRole);
        populateRoleNames();

           javax.swing.GroupLayout RolePanelLayout = new javax.swing.GroupLayout(RolePanel);
           RolePanel.setLayout(RolePanelLayout);
           RolePanelLayout.setHorizontalGroup(
               RolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(ManageRoles)
           );
           RolePanelLayout.setVerticalGroup(
               RolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(ManageRoles)
           );

           AdminPane.addTab("Manage Roles", RolePanel);
           
        LogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
                LogoutBtn.setForeground(new java.awt.Color(204, 0, 0));
                LogoutBtn.setText("Log Out");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                      LogoutBtnActionPerformed(evt);
                   }
               });

                javax.swing.GroupLayout LogoutPanelLayout = new javax.swing.GroupLayout(LogoutPanel);
                LogoutPanel.setLayout(LogoutPanelLayout);
                LogoutPanelLayout.setHorizontalGroup(
                    LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutPanelLayout.createSequentialGroup()
                        .addContainerGap(264, Short.MAX_VALUE)
                        .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(808, 808, 808))
                );
                LogoutPanelLayout.setVerticalGroup(
                    LogoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogoutPanelLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(254, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LogoutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 276, Short.MAX_VALUE))
                );

                AdminPane.addTab("Log Out", jPanel1);

           javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
           getContentPane().setLayout(layout);
           layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(AdminPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
           );
           layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(AdminPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
           );

           pack();
    }
   // </editor-fold>//GEN-END:initComponents

    private void DeleteRoleNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRoleNameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRoleNameComboActionPerformed

    private void UserRoleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRoleComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserRoleComboActionPerformed

    private void UserPswdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPswdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPswdFieldActionPerformed
    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPswdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPswdFieldActionPerformed
   

    private void SearchUserBtnActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String userName = SearchUserField.getText();
        AdminOperations admin = new AdminOperationsImpl();
        UserMasterEO userDetails = admin.findByUserName(userName);
        UserNameField.setEnabled(false);
        UserPswdField.setEditable(true);
//        UserPswdField.setEnabled(false);
        if (userDetails == null) {
            UserNameField.setText("");
            UserPswdField.setText("");
            increaseDialogSize();
            JOptionPane.showMessageDialog(this, "No user found with the given username.", "User Not Found", JOptionPane.ERROR_MESSAGE);
            
           
        } else {
            UserNameField.setText(userDetails.getUsername());
            UserPswdField.setText(userDetails.getPassword());
            UserRoleCombo.setSelectedItem(userDetails.getRole().getRoleName());     
        }
    }


    
    private void UpdateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {       
        String userName =  UserNameField.getText();
        String updatedPassword = UserPswdField.getText();
        String updatedRole = (String)UserRoleCombo.getSelectedItem();
       
        
        if (!validate.validatePassword(updatedPassword)) {
            JOptionPane.showMessageDialog(this, "Invalid password. Password must be strong with alphabets, caps, special symbols, numbers, and minimum 8 characters.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return; 
        }
        
        UserMasterEO user = new UserMasterEO();
        user.setUsername(userName);
        user.setPassword(updatedPassword);
        RoleMasterEO role = new RoleMasterEO();
        role.setRoleName(updatedRole);
        user.setRole(role);
        
        AdminOperations admin = new AdminOperationsImpl();
        admin.updateUser(user);
        
        JOptionPane.showMessageDialog(this, "User updated successfully.", "User Updated", JOptionPane.INFORMATION_MESSAGE);
    }

    private void UpdateUserCnclBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Set the text of the fields to an empty string
        UserNameField.setText("");
        UserPswdField.setText("");
        UserRoleCombo.setSelectedIndex(0);
    }

    
    private void CreateUserBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String userName = UsernameFieldInCreateUser.getText();
        String updatedPassword = new String(PswdFieldInCreateUser.getPassword());
        String updatedRole = (String) RoleComboInCreateUser.getSelectedItem();

        if (userName.isEmpty() || updatedPassword.isEmpty() || updatedRole.isEmpty()) {
            increaseDialogSize();
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Incomplete Information", JOptionPane.ERROR_MESSAGE);
        } else {
            // Validate username uniqueness
            if (!validate.isUniqueUser(userName)) {
                JOptionPane.showMessageDialog(this, "Username already exists. Please choose a different username.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validate username format
            if (!validate.validateName(userName)) {
                JOptionPane.showMessageDialog(this, "Invalid username. Please enter a valid name.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validate password format
            if (!validate.validatePassword(updatedPassword)) {
                JOptionPane.showMessageDialog(this, "Invalid password. Password must be strong with alphabets, caps, special symbols, numbers, and minimum 8 characters.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return; 
            }

            // If all validations pass, proceed to create the user
            UserMasterEO user = new UserMasterEO();
            user.setUsername(userName);
            user.setPassword(updatedPassword);
            RoleMasterEO role = new RoleMasterEO();
            role.setRoleName(updatedRole);
            user.setRole(role);

            AdminOperations admin = new AdminOperationsImpl();
            admin.addNewUser(user);

            JOptionPane.showMessageDialog(this, "User created successfully.", "User Created", JOptionPane.INFORMATION_MESSAGE);
            UsernameFieldInCreateUser.setText("");
            PswdFieldInCreateUser.setText("");
            RoleComboInCreateUser.setSelectedIndex(0);
        }
    }

    private void CancelBtnInCreateUserActionPerformed(java.awt.event.ActionEvent evt) {
            UsernameFieldInCreateUser.setText("");
            PswdFieldInCreateUser.setText("");
            RoleComboInCreateUser.setSelectedIndex(0);
        }

    DefaultTableModel model = null;
    
    private void SearchBtnInDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {
        String userName = UsernameFieldInDeleteUser.getText();
        AdminOperations admin = new AdminOperationsImpl();
        UserMasterEO userDetails = admin.findByUserName(userName);
         model = (DefaultTableModel)TableInDeleteUser.getModel();
        if (userDetails == null) {
            if (model.getRowCount() > 0) {
                // Remove existing row
                model.removeRow(0);
            }
            increaseDialogSize();
            JOptionPane.showMessageDialog(this, "No user found with the given username.", "User Not Found", JOptionPane.ERROR_MESSAGE);
        } else {
            String username = userDetails.getUsername();
            String password = userDetails.getPassword();
            String role = userDetails.getRole().getRoleName();
            
            if (model.getRowCount() > 0) {
                // Remove existing row
                model.setRowCount(0);
            }
            model.addRow(new Object[]{username,password,role});
        }
    }

    
    private void  DeleteExistingUserActionPerformed(java.awt.event.ActionEvent evt) {
        String userName = UsernameFieldInDeleteUser.getText();
        AdminOperations admin = new AdminOperationsImpl();
        admin.deleteExisitingUser(userName);
        
        JOptionPane.showMessageDialog(this, "User '" + userName + "' deleted successfully.", "User Deleted", JOptionPane.INFORMATION_MESSAGE);
        model.setRowCount(0);
    }

    
    private void CancelBtnInDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel model = (DefaultTableModel) TableInDeleteUser.getModel();
        model.setRowCount(0); // Remove all rows from the table
    }

    
    private void SearchBtnInViewUsersActionPerformed(java.awt.event.ActionEvent evt) {
        String username = UserNameFieldInViewUsers.getText();
        AdminOperations admin = new AdminOperationsImpl();
        UserMasterEO user = admin.findByUserName(username);
        DefaultTableModel model = (DefaultTableModel)UserDetailsTableInViewUser.getModel();
        model.setRowCount(0);
        if (user == null) {
            if (model.getRowCount() > 0) {
                model.setRowCount(0);
            }
            increaseDialogSize();
            JOptionPane.showMessageDialog(this, "No user found with the given username.", "User Not Found", JOptionPane.ERROR_MESSAGE);
           
        } else {
            RoleMasterEO role = user.getRole();
            String roleName = role.getRoleName();
            if (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            model.addRow(new Object[]{user.getUsername(), user.getPassword(), roleName});   
        }
    }

        
    // Roles
    private void CreateNewRoleActionPerformed(java.awt.event.ActionEvent evt) {
        String roleName = RoleNameField.getText();
        JTextArea textArea = (JTextArea) jScrollPane1.getViewport().getView();
        String roleDesc = textArea.getText();
            
        // Check if roleName or roleDesc is empty
        if (roleName.isEmpty() || roleDesc.isEmpty()) {
            increaseDialogSize(); 
            JOptionPane.showMessageDialog(this, "Please enter both role name and description.", "Incomplete Information", JOptionPane.ERROR_MESSAGE);
        } else {
            // Validate the role name
            if (!validate.validateName(roleName)) {
                JOptionPane.showMessageDialog(this, "Invalid role name. Please enter a valid name.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return; 
            }
            
            // Validate the uniqueness of the role name
            if (!validate.isUniqueRole(roleName)) {
                JOptionPane.showMessageDialog(this, "Role name already exists. Please choose a different role name.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

      
        RoleMasterEO role = new RoleMasterEO();
        role.setRoleName(roleName);
        role.setRoleDesc(roleDesc);
        AdminOperations admin = new AdminOperationsImpl();
        admin.addNewRole(role);
                
        JOptionPane.showMessageDialog(this, "Role created successfully.", "Role Created", JOptionPane.INFORMATION_MESSAGE);
        populateRoleNames();
        RoleNameField.setText("");
        textArea.setText("");   
    }


    
    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Set the text of the two fields to an empty string
        RoleNameField.setText("");
        JTextArea textArea = (JTextArea) jScrollPane1.getViewport().getView();
        textArea.setText("");
    }

    
    
    private void SearchRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String roleName = RoleNameFieldUpdate.getText();
        jTextArea2.setEditable(true);
        if (roleName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a role name.", "Incomplete Information", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        AdminOperations admin = new AdminOperationsImpl();
        RoleMasterEO role =  admin.findByRoleName(roleName);
        JTextArea textArea = (JTextArea) jScrollPane5.getViewport().getView();
        if (role == null) {
            textArea.setText("");
            increaseDialogSize();
            JOptionPane.showMessageDialog(this, "No role found with the given name.", "Role Not Found", JOptionPane.ERROR_MESSAGE);
        
        }  
        else {
        // Clear the content of the role description field
        textArea.setText("");
        Font font = textArea.getFont();
            textArea.setFont(new Font(font.getName(), font.getStyle(), 18));
        textArea.setText(role.getRoleDesc());
        }
    }

        
    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {
        JTextArea textArea = (JTextArea) jScrollPane5.getViewport().getView();
    
        String roleDesc = textArea.getText();
        RoleMasterEO role = new RoleMasterEO();
        role.setRoleName(RoleNameFieldUpdate.getText());
        role.setRoleDesc(roleDesc);
        AdminOperations admin = new AdminOperationsImpl();
        admin.updateRole(role);
        
        JOptionPane.showMessageDialog(this, "Role updated successfully.", "Role Updated", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void UpdateCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
            JTextArea textArea = (JTextArea) jScrollPane5.getViewport().getView();
            textArea.setText("");
        }

    
    private void RoleDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String roleName =(String) DeleteRoleNameCombo.getSelectedItem();
        AdminOperations admin = new AdminOperationsImpl();
        admin.deleteRole(roleName);
        
        // Remove the deleted role from the combo box
        DeleteRoleNameCombo.removeItem(roleName);
        increaseDialogSize();
        JOptionPane.showMessageDialog(this, "Role '" + roleName + "' deleted successfully.", "Role Deleted", JOptionPane.INFORMATION_MESSAGE);
    }


    private void RoleDeleteCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {
           DeleteRoleNameCombo.setSelectedIndex(0);
           populateRoleNames();
        }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String roleName = jTextField1.getText();
        AdminOperations admin = new AdminOperationsImpl();
        RoleMasterEO role = admin.findByRoleName(roleName);
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        

        if (role == null) {
            increaseDialogSize();
            JOptionPane.showMessageDialog(this, "Role name not found.", "Role Not Found", JOptionPane.ERROR_MESSAGE);
        } else {
        
            model.addRow(new Object[]{role.getRoleName(), role.getRoleDesc()});
            System.out.println(role.getRoleName()+" "+role.getRoleDesc());
        }
    }
    
    private void SearchAllUsersActionPerformed(java.awt.event.ActionEvent evt) {

        AdminOperations admin = new AdminOperationsImpl();
        List<UserMasterEO> users = admin.fetchAllUsers();
       DefaultTableModel model = (DefaultTableModel) UserDetailsTableInViewUser.getModel();
        
        model.setRowCount(0);
        for(UserMasterEO user: users) {
            RoleMasterEO role = user.getRole();
            String roleName = role.getRoleName();
            model.addRow(new Object[]{user.getUsername(), user.getPassword(), roleName});   
        }

    }
    
    private void SearchAllRolesActionPerformed(java.awt.event.ActionEvent evt) {

        AdminOperations admin = new AdminOperationsImpl();
        List<RoleMasterEO> roles = admin.fetchAllRoles();
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        for(RoleMasterEO role: roles) {
            model.addRow(new Object[]{role.getRoleName(), role.getRoleDesc()});
        }

    }



    private void increaseDialogSize() {
        UIManager.put("OptionPane.minimumSize", new Dimension(500, 350));
    }
    
    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {
            this.dispose();
            Login login = new Login();
        }
    
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AdminPane;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton CreateNewRole;
    private javax.swing.JPanel CreateRole;
    private javax.swing.JLabel CreateRoleTitle;
    private javax.swing.JPanel DeleteRole;
    private javax.swing.JComboBox<String> DeleteRoleNameCombo;
    private javax.swing.JLabel DeleteRoleNameLabel;
    private javax.swing.JLabel DeleteRoleTitle;
    private javax.swing.JPanel DeleteUser;
    private javax.swing.JTabbedPane ManageRoles;
    private javax.swing.JLabel NewRoleLabel;
    private javax.swing.JButton RoleDeleteBtn;
    private javax.swing.JButton RoleDeleteCancelBtn;
    private javax.swing.JButton RoleDescEditBtn;
    private javax.swing.JScrollPane RoleDescField;
    private javax.swing.JScrollPane RoleDescScroll;
    private javax.swing.JLabel RoleDescUpdate;
    private javax.swing.JLabel RoleDescription;
    private javax.swing.JLabel RoleDetailsTitle;
    private javax.swing.JLabel RoleName;
    private javax.swing.JTextField RoleNameField;
    private javax.swing.JTextField RoleNameFieldUpdate;
    private javax.swing.JLabel RoleNameUpdate;
    private javax.swing.JPanel RolePanel;
    private javax.swing.JButton SearchRoleBtn;
    private javax.swing.JButton SearchUserBtn;
    private javax.swing.JTextField SearchUserField;
    private javax.swing.JLabel SearchUserLabel;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton UpdateCancelBtn;
    private javax.swing.JPanel UpdateRole;
    private javax.swing.JLabel UpdateRoleTitle;
    private javax.swing.JPanel UpdateUser;
    private javax.swing.JButton UpdateUserBtn;
    private javax.swing.JButton UpdateUserCnclBtn;
    private javax.swing.JLabel UpdateUserLabel;
    private javax.swing.JLabel UpdateUserPswdLabel;
    private javax.swing.JLabel UserDetailsTitle;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JButton UserPswdEditBtn;
    private javax.swing.JPasswordField UserPswdField;
    private javax.swing.JComboBox<String> UserRoleCombo;
    private javax.swing.JPanel ViewRole;
    private javax.swing.JPanel ViewUsers;
    private javax.swing.JButton CreateUserBtn;
    private javax.swing.JButton CancelBtnInCreateUser;
    private javax.swing.JButton SearchBtnInDeleteUser;
    private javax.swing.JButton DeleteExistingUser;
    private javax.swing.JButton CancelBtnInDeleteUser;
    private javax.swing.JComboBox<String> RoleComboInCreateUser;
    private javax.swing.JLabel UsernameLabelInCreateUser;
    private javax.swing.JLabel PasswordLabelInCreateUser;
    private javax.swing.JLabel AssignRoleLabelInCreateUser;
    private javax.swing.JLabel UsernameLableInCreateUser5;
    private javax.swing.JLabel UsernameLabelInDeleteUser;
    private javax.swing.JLabel UserDetailsTitleInDeleteUser;
    private javax.swing.JLabel CreateUserTitle3;
    private javax.swing.JPanel CreateUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTable TableInDeleteUser;
    private javax.swing.JTable UserDetailsTableInViewUser;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField UsernameFieldInCreateUser;
    private JPasswordField PswdFieldInCreateUser;
    private javax.swing.JTextField UsernameFieldInDeleteUser;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel UsernameLableInCreateUser;
    private javax.swing.JLabel CreateUserTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton LogoutBtn;
        private javax.swing.JPanel LogoutPanel;
    private javax.swing.JTextField UserNameFieldInViewUsers;
    private javax.swing.JButton SearchBtnInViewUsers;
    private javax.swing.JButton SearchAllUsers;
    private javax.swing.JButton SearchAllRoles;
    // End of variables declaration//GEN-END:variables
}
