/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.ui;

import com.sun.corba.se.impl.protocol.SpecialMethod;

import java.awt.Dimension;
import java.awt.Font;

import java.io.File;

import java.io.FileInputStream;

import java.sql.Timestamp;

import java.time.LocalDate;

import java.util.List;

import javax.swing.JFileChooser;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.JTableHeader;

import tms.business.ClerkOperations;
import tms.business.TCopOperations;
import tms.business.impl.ClerkOperationsImpl;

import tms.business.impl.TCopOperationsImpl;

import tms.entities.OffenceDetailsEO;
import tms.entities.OffenceEO;
import tms.entities.RegDetailsEO;
import tms.entities.UserMasterEO;

import tms.util.Validation;

/**
 *
 * @author reddirani.battuluri
 */
public class Clerk extends javax.swing.JFrame {

    /**
     * Creates new form Clerk
     */
    public Clerk() {
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ManageOffences = new javax.swing.JPanel();
        ManageOffencesTab = new javax.swing.JTabbedPane();
        RaiseOffenceTab = new javax.swing.JPanel();
        RaiseOffencePanel = new javax.swing.JPanel();
        VehicleNumLableInRaiseOffence = new javax.swing.JLabel();
        VehNumFieldInRaiseOffence = new javax.swing.JTextField();
        ImageLabelRaiseOffence = new javax.swing.JLabel();
        OffenceStatusLabelInRaiseOffence = new javax.swing.JLabel();
        OffenceStatusComboBoxInRaiseOffence = new javax.swing.JComboBox<>();
        OffenceIdLabelInRaiseOffence = new javax.swing.JLabel();
        OffenceIdFieldInRaiseOffence = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        PlaceLabelInRaiseOffence = new javax.swing.JLabel();
        PlaceFieldInRaiseOffence = new javax.swing.JTextField();
        ReportedByLabelInRaiseOffence = new javax.swing.JLabel();
        ReportedByFieldInRaiseOffence = new javax.swing.JTextField();
        RaiseBtnInRaiseOffence = new javax.swing.JButton();
        CancelBtnInRaiseOffence = new javax.swing.JButton();
        UploadBtnRaiseOffence = new javax.swing.JButton();
        OffenceDetailsTitle = new javax.swing.JLabel();
        ClearOffencePanel = new javax.swing.JPanel();
        ClearOffenceTitle = new javax.swing.JLabel();
        VehNumLableInClearOffence = new javax.swing.JLabel();
        VehNumFieldInClearOffence = new javax.swing.JTextField();
        SearchBtnInClearOffence = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OffencesTableInClearOffence = new javax.swing.JTable();
        ClearBtnInClearOffence = new javax.swing.JButton();
        CancelBtnInClearOffence = new javax.swing.JButton();
        ViewOffenceTab = new javax.swing.JPanel();
        ViewOffencePanel = new javax.swing.JPanel();
        OffenceHistoryTitle = new javax.swing.JLabel();
        VehNoViewOffencesLabel = new javax.swing.JLabel();
        VehNumFielInViewOffence = new javax.swing.JTextField();
        SearchBtnInViewOffences = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        OffenceHistoryTabel = new javax.swing.JTable();
        LogoutPannel = new javax.swing.JPanel();
        LogoutBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        SearchAllOffences = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(2000, 1000));
        jTabbedPane1.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 36));
        ManageOffencesTab.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 36));

        VehicleNumLableInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        VehicleNumLableInRaiseOffence.setText("Vehicle Number");
        VehNumFieldInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 18));

        ImageLabelRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        ImageLabelRaiseOffence.setText("Image");

        OffenceStatusLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        OffenceStatusLabelInRaiseOffence.setText("Offence Status");

        OffenceStatusComboBoxInRaiseOffence.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UnPaid", "Paid" }));
        OffenceStatusComboBoxInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22));
        
        OffenceIdLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        OffenceIdLabelInRaiseOffence.setText("Offence Id");
        
        OffenceIdFieldInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 18));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setText("Time");

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 18));

        PlaceLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        PlaceLabelInRaiseOffence.setText("Place");
        
        PlaceFieldInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 18));

        ReportedByLabelInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        ReportedByLabelInRaiseOffence.setText("Reported By");
        
        ReportedByFieldInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 18));

        RaiseBtnInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        RaiseBtnInRaiseOffence.setForeground(new java.awt.Color(153, 0, 0));
        RaiseBtnInRaiseOffence.setText("Raise");
        RaiseBtnInRaiseOffence.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        RaiseBtnInRaiseOffenceActionPerformed(evt);
                    }
                });

        CancelBtnInRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        CancelBtnInRaiseOffence.setForeground(new java.awt.Color(153, 0, 0));
        CancelBtnInRaiseOffence.setText("Cancel");
        CancelBtnInRaiseOffence.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      CancelBtnInRaiseOffenceActionPerformed(evt);
                  }
              });

        UploadBtnRaiseOffence.setText("Upload");
        UploadBtnRaiseOffence.setFont(new java.awt.Font("Tahoma", 1, 22));
        UploadBtnRaiseOffence.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        UploadBtnRaiseOffenceActionPerformed(evt);
                    }
                });

        OffenceDetailsTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        OffenceDetailsTitle.setForeground(new java.awt.Color(204, 0, 0));
        OffenceDetailsTitle.setText("Offence Details");

        javax.swing.GroupLayout RaiseOffencePanelLayout = new javax.swing.GroupLayout(RaiseOffencePanel);
               RaiseOffencePanel.setLayout(RaiseOffencePanelLayout);
               RaiseOffencePanelLayout.setHorizontalGroup(
                   RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                       .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                               .addGap(600, 600, 600)
                               .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(VehicleNumLableInRaiseOffence,  javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(OffenceStatusLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(OffenceIdLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(PlaceLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(ReportedByLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(ImageLabelRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                               .addGap(38, 38, 38)
                               .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(VehNumFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(OffenceStatusComboBoxInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(OffenceIdFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 200,  javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(PlaceFieldInRaiseOffence,  javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(ReportedByFieldInRaiseOffence,  javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(UploadBtnRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                           .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
        .addGap(600, 600, 600)
                               .addComponent(RaiseBtnInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                               .addGap(43, 43, 43)
                               .addComponent(CancelBtnInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
        .addGap(600, 600, 600)
                               .addComponent(OffenceDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                       .addContainerGap(1458, Short.MAX_VALUE))
               );
               RaiseOffencePanelLayout.setVerticalGroup(
                   RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(RaiseOffencePanelLayout.createSequentialGroup()
                             .addGap(70,70,70)
                       .addComponent(OffenceDetailsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(40, 40, 40)
                       .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(VehNumFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(VehicleNumLableInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(25, 25, 25)
                       .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(ImageLabelRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(UploadBtnRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(25, 25, 25)
                       .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(OffenceStatusLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(OffenceStatusComboBoxInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(25, 25, 25)
                       .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(OffenceIdLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(OffenceIdFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(25, 25, 25)
                       .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(25, 25, 25)
                       .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(PlaceLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(PlaceFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(25, 25, 25)
                       .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(ReportedByLabelInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ReportedByFieldInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(52, 52, 52)
                       .addGroup(RaiseOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(RaiseBtnInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(CancelBtnInRaiseOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addContainerGap(587, Short.MAX_VALUE))
               );

               javax.swing.GroupLayout RaiseOffenceTabLayout = new javax.swing.GroupLayout(RaiseOffenceTab);
               RaiseOffenceTab.setLayout(RaiseOffenceTabLayout);
               RaiseOffenceTabLayout.setHorizontalGroup(
                   RaiseOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGap(0, 2000, Short.MAX_VALUE)
                   .addGroup(RaiseOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                       .addGroup(RaiseOffenceTabLayout.createSequentialGroup()
                           .addGap(0, 0, Short.MAX_VALUE)
                           .addComponent(RaiseOffencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGap(0, 0, Short.MAX_VALUE)))
               );
               RaiseOffenceTabLayout.setVerticalGroup(
                   RaiseOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGap(0, 1000, Short.MAX_VALUE)
                   .addGroup(RaiseOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                       .addGroup(RaiseOffenceTabLayout.createSequentialGroup()
                           .addGap(0, 0, Short.MAX_VALUE)
                           .addComponent(RaiseOffencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGap(0, 0, Short.MAX_VALUE)))
               );

        ManageOffencesTab.addTab("Raise Offence", RaiseOffenceTab);

        ClearOffenceTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        ClearOffenceTitle.setForeground(new java.awt.Color(153, 0, 0));
        ClearOffenceTitle.setText("Clear Offences");

        VehNumLableInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        VehNumLableInClearOffence.setText("Vehicle Number");

        SearchBtnInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        SearchBtnInClearOffence.setForeground(new java.awt.Color(153, 0, 0));
        SearchBtnInClearOffence.setText("Search");
        SearchBtnInClearOffence.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchBtnInClearOffenceActionPerformed(evt);
                    }
                });
       
        JTableHeader head2 = OffencesTableInClearOffence.getTableHeader();
        head2.setFont(new Font("SansSerif", Font.ITALIC, 17));
        OffencesTableInClearOffence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
//                {null, null,  null, null, null, null, null, null},
//                {null, null, null, null, null, null, null, null},
//                {null, null,  null, null, null, null, null, null},
//                {null, null,  null, null, null, null, null, null}
            },
            new String [] {
                "Select", "Vehicle Number",  "Offence Detail Id", "Offence Status", "Offence ID", "Time", "Place", "Reported By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OffencesTableInClearOffence);
        Font tableFont = OffencesTableInClearOffence.getFont();
              OffencesTableInClearOffence.setFont(new Font(tableFont.getName(), tableFont.getStyle(), 18));
              OffencesTableInClearOffence.setRowHeight(30);

        ClearBtnInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        ClearBtnInClearOffence.setForeground(new java.awt.Color(153, 0, 0));
        ClearBtnInClearOffence.setText("Clear");
        ClearBtnInClearOffence.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        ClearBtnInClearOffenceActionPerformed(evt);
                    }
                });

        CancelBtnInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        CancelBtnInClearOffence.setForeground(new java.awt.Color(204, 0, 0));
        CancelBtnInClearOffence.setText("Cancel");
        VehNumFieldInClearOffence.setFont(new java.awt.Font("Tahoma", 1, 18));

        javax.swing.GroupLayout ClearOffencePanelLayout = new javax.swing.GroupLayout(ClearOffencePanel);
        ClearOffencePanel.setLayout(ClearOffencePanelLayout);
        ClearOffencePanelLayout.setHorizontalGroup(
            ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                .addGroup(ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(670, 670, 670)
                        .addComponent(ClearOffenceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(620,620,620)
                        .addComponent(VehNumLableInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VehNumFieldInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SearchBtnInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(350,350,350)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                        .addGap(670,670,670)
                        .addComponent(ClearBtnInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(CancelBtnInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ClearOffencePanelLayout.setVerticalGroup(
            ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClearOffencePanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(ClearOffenceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VehNumLableInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VehNumFieldInClearOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtnInClearOffence,javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150,150,150)
                .addGroup(ClearOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBtnInClearOffence,javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelBtnInClearOffence,javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        ManageOffencesTab.addTab("Clear Offence", ClearOffencePanel);

        OffenceHistoryTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        OffenceHistoryTitle.setForeground(new java.awt.Color(204, 0, 0));
        OffenceHistoryTitle.setText("Offence History");

        VehNoViewOffencesLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        VehNoViewOffencesLabel.setText("Vehicle Number");

        VehNumFielInViewOffence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehNumFielInViewOffenceActionPerformed(evt);
            }
        });
        VehNumFielInViewOffence.setFont(new java.awt.Font("Tahoma", 1, 18));

        SearchBtnInViewOffences.setText("Search");
        SearchBtnInViewOffences.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchBtnInViewOffencesActionPerformed(evt);
                    }
                });
        SearchBtnInViewOffences.setFont(new java.awt.Font("Tahoma", 1, 22));
        SearchBtnInViewOffences.setForeground(new java.awt.Color(204, 0, 0));
        
        JTableHeader head1 = OffenceHistoryTabel.getTableHeader();
        head1.setFont(new Font("SansSerif", Font.ITALIC, 17));
        OffenceHistoryTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
//                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vehicle Number",  "Offence Detail Id", "Offence Status", "Offence Id", "Time", "Place", "Reported By"
            }
        ));
        jScrollPane6.setViewportView(OffenceHistoryTabel);
      
        OffenceHistoryTabel.setFont(new Font(tableFont.getName(), tableFont.getStyle(), 18));
        OffenceHistoryTabel.setRowHeight(30);
        
        SearchAllOffences.setText("Search All Offences");
        SearchAllOffences.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        SearchAllOffencesActionPerformed(evt);
                    }
                });
        SearchAllOffences.setFont(new java.awt.Font("Tahoma", 1, 22));
        SearchAllOffences.setForeground(new java.awt.Color(204, 0, 0));

//        javax.swing.GroupLayout ViewOffencePanelLayout = new javax.swing.GroupLayout(ViewOffencePanel);
//        ViewOffencePanel.setLayout(ViewOffencePanelLayout);
//        ViewOffencePanelLayout.setHorizontalGroup(
//            ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
//                .addGroup(ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(ViewOffencePanelLayout.createSequentialGroup()
//                        .addGap(500,500,500)
//                        .addComponent(VehNoViewOffencesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(33, 33, 33)
//                        .addComponent(VehNumFielInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(18, 18, 18)
//                        .addComponent(SearchBtnInViewOffences, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(0, 342, Short.MAX_VALUE)
//        .addComponent(SearchAllOffences, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(33, 33, 33))
//                          
//                    .addGroup(ViewOffencePanelLayout.createSequentialGroup()
//                        .addGap(370,370,370)
//                        .addComponent(jScrollPane6,javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE )))
//                .addContainerGap())
//            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
//                .addGap(537,537,537)
//                .addComponent(OffenceHistoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//     
//        );
//        ViewOffencePanelLayout.setVerticalGroup(
//            ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(ViewOffencePanelLayout.createSequentialGroup()
//                .addGap(17, 17, 17)
//                .addComponent(OffenceHistoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(130, 130, 130)
//                .addGroup(ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(VehNoViewOffencesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(VehNumFielInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(SearchBtnInViewOffences)
//        .addComponent(SearchAllOffences, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addGap(160, 160, 160)
//                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap(196, Short.MAX_VALUE))
//        );
//
//        javax.swing.GroupLayout ViewOffenceTabLayout = new javax.swing.GroupLayout(ViewOffenceTab);
//        ViewOffenceTab.setLayout(ViewOffenceTabLayout);
//        ViewOffenceTabLayout.setHorizontalGroup(
//            ViewOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(ViewOffencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        ViewOffenceTabLayout.setVerticalGroup(
//            ViewOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(ViewOffencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
            
            javax.swing.GroupLayout ViewOffencePanelLayout = new javax.swing.GroupLayout(ViewOffencePanel);
            ViewOffencePanel.setLayout(ViewOffencePanelLayout);
            ViewOffencePanelLayout.setHorizontalGroup(
                ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                    .addGap(300, 300, 300)
                    .addComponent(VehNoViewOffencesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(VehNumFielInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(SearchBtnInViewOffences, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(278,278,278)
                    .addComponent(SearchAllOffences, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE) // Moved SearchAllOffences button here
                    .addGap(342, 342, 342))
                .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                    .addGap(370, 370, 370)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                    .addGap(537, 537, 537)
                    .addComponent(OffenceHistoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            
            ViewOffencePanelLayout.setVerticalGroup(
                ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewOffencePanelLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(OffenceHistoryTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(130, 130, 130)
                    .addGroup(ViewOffencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(VehNoViewOffencesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VehNumFielInViewOffence, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SearchBtnInViewOffences)
                        .addComponent(SearchAllOffences, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)) // SearchAllOffences button
                    .addGap(160, 160, 160)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(196, Short.MAX_VALUE))
            );

        javax.swing.GroupLayout ViewOffenceTabLayout = new javax.swing.GroupLayout(ViewOffenceTab);
        ViewOffenceTab.setLayout(ViewOffenceTabLayout);
        ViewOffenceTabLayout.setHorizontalGroup(
            ViewOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewOffencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ViewOffenceTabLayout.setVerticalGroup(
            ViewOffenceTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewOffencePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );


        ManageOffencesTab.addTab("ViewOffences", ViewOffenceTab);

        javax.swing.GroupLayout ManageOffencesLayout = new javax.swing.GroupLayout(ManageOffences);
        ManageOffences.setLayout(ManageOffencesLayout);
        ManageOffencesLayout.setHorizontalGroup(
            ManageOffencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageOffencesTab)
        );
        ManageOffencesLayout.setVerticalGroup(
            ManageOffencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageOffencesTab)
        );

        jTabbedPane1.addTab("Manage Offences", ManageOffences);
        
        LogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
               LogoutBtn.setForeground(new java.awt.Color(204, 0, 0));
               LogoutBtn.setText("Log Out");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
                   public void actionPerformed(java.awt.event.ActionEvent evt) {
                       LogoutBtnActionPerformed(evt);
                   }
               });

               javax.swing.GroupLayout LogoutPannelLayout = new javax.swing.GroupLayout(LogoutPannel);
               LogoutPannel.setLayout(LogoutPannelLayout);
               LogoutPannelLayout.setHorizontalGroup(
                   LogoutPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(LogoutPannelLayout.createSequentialGroup()
                       .addGap(580, 580, 580)
                       .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addContainerGap(265, Short.MAX_VALUE))
               );
               LogoutPannelLayout.setVerticalGroup(
                   LogoutPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(LogoutPannelLayout.createSequentialGroup()
                       .addGap(410, 410, 410)
                       .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addContainerGap(193, Short.MAX_VALUE))
               );

               javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
               jPanel1.setLayout(jPanel1Layout);
               jPanel1Layout.setHorizontalGroup(
                   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(LogoutPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addContainerGap(1152, Short.MAX_VALUE))
               );
               jPanel1Layout.setVerticalGroup(
                   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(LogoutPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addContainerGap(520, Short.MAX_VALUE))
               );

               jTabbedPane1.addTab("Log Out", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VehNumFielInViewOffenceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    File selectedFile = null;
    private void UploadBtnRaiseOffenceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
             int returnValue = fileChooser.showOpenDialog(null);
             if (returnValue == JFileChooser.APPROVE_OPTION) {
               selectedFile = fileChooser.getSelectedFile();

             }
    }
    

    Validation validate = new Validation();

    private void RaiseBtnInRaiseOffenceActionPerformed(java.awt.event.ActionEvent evt) {
        if (VehNumFieldInRaiseOffence.getText().isEmpty() || OffenceIdFieldInRaiseOffence.getText().isEmpty() || PlaceFieldInRaiseOffence.getText().isEmpty() || ReportedByFieldInRaiseOffence.getText().isEmpty() || selectedFile == null) {
            increaseDialogSize();
            JOptionPane.showMessageDialog(this, "Please fill in all fields and select an image.", "Missing Information", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String vehicleNum = VehNumFieldInRaiseOffence.getText();
        String offenceIdText = OffenceIdFieldInRaiseOffence.getText();
        String place = PlaceFieldInRaiseOffence.getText();
        String reporter = ReportedByFieldInRaiseOffence.getText();
        
        if (!validate.isValidVehNum(vehicleNum)) {
            JOptionPane.showMessageDialog(this, "Invalid vehicle number.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!validate.isValidOffenceId(offenceIdText)) {
            JOptionPane.showMessageDialog(this, "Invalid offence ID. Please enter a valid ID containing only numbers.", "Invalid Offence ID", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
       
        int offenceId = Integer.parseInt(offenceIdText);
        if (!validate.isValidOffenceId(offenceId)) {
            JOptionPane.showMessageDialog(this, "Invalid offence ID.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!validate.isValidReporter(reporter)) {
            JOptionPane.showMessageDialog(this, "Invalid reporter username.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        OffenceDetailsEO offence = new OffenceDetailsEO();
        RegDetailsEO reg = new RegDetailsEO();
        reg.setVehNo(vehicleNum);
        offence.setRegDetails(reg);
        
        String imagePath = String.valueOf(selectedFile);
        FileInputStream fis;
        byte[] image = null;
        try {
            fis = new FileInputStream(imagePath);
            image = new byte[fis.available()];
            fis.read(image);
        } catch (Exception e) {
            System.out.println("Image not uploaded");
        }     
        offence.setImage(image);
        
        offence.setOffenceStatus((String) OffenceStatusComboBoxInRaiseOffence.getSelectedItem());
        OffenceEO offenceEo = new OffenceEO();
        offenceEo.setOffenceId(offenceId);
        offence.setOffence(offenceEo);
        offence.setTime(new java.sql.Timestamp(((java.util.Date) jSpinner1.getValue()).getTime()));
        offence.setPlace(place);
        UserMasterEO user = new UserMasterEO();
        user.setUsername(reporter);
        offence.setUser(user);
        
        ClerkOperations clerk = new ClerkOperationsImpl();
        clerk.raiseOffence(offence);
        
        JOptionPane.showMessageDialog(this, "Offence raised successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        VehNumFieldInRaiseOffence.setText("");
            OffenceIdFieldInRaiseOffence.setText("");
            PlaceFieldInRaiseOffence.setText("");
            ReportedByFieldInRaiseOffence.setText("");
            OffenceStatusComboBoxInRaiseOffence.setSelectedIndex(0);
            jSpinner1.setValue(new java.util.Date());
            selectedFile = null;
    }

    private void CancelBtnInRaiseOffenceActionPerformed(java.awt.event.ActionEvent evt) {
            VehNumFieldInRaiseOffence.setText("");
                OffenceIdFieldInRaiseOffence.setText("");
                PlaceFieldInRaiseOffence.setText("");
                ReportedByFieldInRaiseOffence.setText("");
                OffenceStatusComboBoxInRaiseOffence.setSelectedIndex(0);
                jSpinner1.setValue(new java.util.Date());
                selectedFile = null;
          
        }

    private void clearFieldsAndTable() {
        DefaultTableModel model = (DefaultTableModel)OffencesTableInClearOffence.getModel();
        model.setRowCount(0);
       
    }

//    private void SearchBtnInClearOffenceActionPerformed(java.awt.event.ActionEvent evt) {
//        clearFieldsAndTable();
//        
//        String vehicleNum = VehNumFieldInClearOffence.getText();
//        System.out.println(vehicleNum);
//        TCopOperations clerk = new TCopOperationsImpl();
//        
//        List<OffenceDetailsEO> offence = clerk.fetchAllOffencesCommited(vehicleNum);
//        System.out.println(offence);
//        
//        if (offence.isEmpty()) {
//            clearFieldsAndTable();
//            increaseDialogSize();
//            JOptionPane.showMessageDialog(this, "No offences found for the given vehicle number.", "No Offences", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//        
//        DefaultTableModel model = (DefaultTableModel)OffencesTableInClearOffence.getModel();
//        for(OffenceDetailsEO detail : offence) {
//            RegDetailsEO reg = detail.getRegDetails();
//            OffenceEO offenceId = detail.getOffence();
//            UserMasterEO user = detail.getUser();
//            if(detail.getOffenceStatus().equals("UnPaid")) {
//          
//                model.addRow(new Object[]{false, reg.getVehNo(), detail.getOffenceDetailId(), detail.getOffenceStatus(),
//                                           offenceId.getOffenceId(), detail.getTime(), detail.getPlace(), user.getUsername()});
//            }
//        }
//    }
//
//
//
//    private void ClearBtnInClearOffenceActionPerformed(java.awt.event.ActionEvent evt) {
//        String vehicleNum = VehNumFieldInClearOffence.getText();
//        TCopOperations clerk = new TCopOperationsImpl();
//        System.out.println("Before offence obj");
//        List<OffenceDetailsEO> offence = clerk.fetchAllOffencesCommited(vehicleNum);
//        System.out.println("Before offence obj");
//        int count = 0;
//        for(OffenceDetailsEO detail: offence) {
//            System.out.println(model.)
//            boolean isSelected = (Boolean)OffencesTableInClearOffence.getValueAt(count++, 0);
//            
//            if(isSelected) {
//                clerk.clearOffence(detail);
//            }
//        }
//        
//        JOptionPane.showMessageDialog(this, "Offences cleared successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
//    }
    
     DefaultTableModel model = null;
     private void SearchBtnInClearOffenceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String vehicleNum = VehNumFieldInClearOffence.getText();
        model = (DefaultTableModel)OffencesTableInClearOffence.getModel();
       
        if (vehicleNum.isEmpty()) {
                model.setRowCount(0);
                increaseDialogSize();
                JOptionPane.showMessageDialog(null, "Please enter a vehicle number.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        ClerkOperations clerk = new ClerkOperationsImpl();
        
        List<OffenceDetailsEO> offence = clerk.fetchAllOffencesCommited(vehicleNum);
        if (offence.isEmpty()) {
                model.setRowCount(0);
                increaseDialogSize();
                JOptionPane.showMessageDialog(null, "Please enter a valid vehicle number.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        if (model.getRowCount() > 0) {
            // Remove existing row
            model.setRowCount(0);
        } 
        
        for(OffenceDetailsEO detail : offence) {
         RegDetailsEO reg = detail.getRegDetails();
         OffenceEO offenceId =    detail.getOffence();
        UserMasterEO user = detail.getUser();
            
            if(detail.getOffenceStatus().equals("UnPaid")){
            model.addRow(new Object[]{false,reg.getVehNo(), detail.getOffenceDetailId(),detail.getOffenceStatus()
                                      ,offenceId.getOffenceId(),detail.getTime(),detail.getPlace(),user.getUsername()});
            }
        }
    }

    private void ClearBtnInClearOffenceActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String vehicleNum = VehNumFieldInClearOffence.getText();
        ClerkOperations clerk = new ClerkOperationsImpl();
        
        List<OffenceDetailsEO> offence = clerk.fetchAllOffencesCommited(vehicleNum);
        System.out.println(offence.size());
        int count = 0;
        for(OffenceDetailsEO detail: offence) {

            if(detail.getOffenceStatus().equals("UnPaid")) {
            boolean isSelected = (Boolean)OffencesTableInClearOffence.getValueAt(count++, 0);
            
            if(isSelected) {
                clerk.clearOffence(detail);
                
            }
            }

        }
        
        JOptionPane.showMessageDialog(this, "Offences cleared successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

    }



    private void clearFields() {
        DefaultTableModel model = (DefaultTableModel)OffenceHistoryTabel.getModel();
        model.setRowCount(0);
        
    }
    private void SearchBtnInViewOffencesActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel model = (DefaultTableModel)OffenceHistoryTabel.getModel();
        model.setRowCount(0);
        String vehicleNum = VehNumFielInViewOffence.getText();
        ClerkOperations clerk = new ClerkOperationsImpl();
        
        List<OffenceDetailsEO> offence = clerk.fetchAllOffencesCommited(vehicleNum);
        
        if (offence.isEmpty()) {
            clearFields();
            increaseDialogSize();
            JOptionPane.showMessageDialog(this, "No offences found for the given vehicle number.", "No Offences", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
       
        for(OffenceDetailsEO detail : offence) {
            RegDetailsEO reg = detail.getRegDetails();
            OffenceEO offenceId = detail.getOffence();
            UserMasterEO user = detail.getUser();
            
            model.addRow(new Object[]{reg.getVehNo(), detail.getOffenceDetailId(), detail.getOffenceStatus(),
                                       offenceId.getOffenceId(), detail.getTime(), detail.getPlace(), user.getUsername()});
        }
    }
    
    private void SearchAllOffencesActionPerformed(java.awt.event.ActionEvent evt) {
        DefaultTableModel model = (DefaultTableModel)OffenceHistoryTabel.getModel();
        model.setRowCount(0);
        ClerkOperations clerk = new ClerkOperationsImpl();
        
        List<OffenceDetailsEO> offence = clerk.fetchAllOffences();
        
     
        
       
        for(OffenceDetailsEO detail : offence) {
            RegDetailsEO reg = detail.getRegDetails();
            OffenceEO offenceId = detail.getOffence();
            UserMasterEO user = detail.getUser();
            
            model.addRow(new Object[]{reg.getVehNo(), detail.getOffenceDetailId(), detail.getOffenceStatus(),
                                       offenceId.getOffenceId(), detail.getTime(), detail.getPlace(), user.getUsername()});
        }
    }

    
    private void increaseDialogSize() {
        UIManager.put("OptionPane.minimumSize", new Dimension(500, 350));
    }
    
    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {
           this.dispose();
           Login login = new Login();
       }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clerk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clerk().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn;
       private javax.swing.JPanel LogoutPannel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton CancelBtnInClearOffence;
    private javax.swing.JButton CancelBtnInRaiseOffence;
    private javax.swing.JButton ClearBtnInClearOffence;
    private javax.swing.JPanel ClearOffencePanel;
    private javax.swing.JLabel ClearOffenceTitle;
    private javax.swing.JLabel ImageLabelRaiseOffence;
    private javax.swing.JPanel ManageOffences;
    private javax.swing.JTabbedPane ManageOffencesTab;
    private javax.swing.JLabel OffenceDetailsTitle;
    private javax.swing.JTable OffenceHistoryTabel;
    private javax.swing.JLabel OffenceHistoryTitle;
    private javax.swing.JTextField OffenceIdFieldInRaiseOffence;
    private javax.swing.JLabel OffenceIdLabelInRaiseOffence;
    private javax.swing.JComboBox<String> OffenceStatusComboBoxInRaiseOffence;
    private javax.swing.JLabel OffenceStatusLabelInRaiseOffence;
    private javax.swing.JTable OffencesTableInClearOffence;
    private javax.swing.JTextField PlaceFieldInRaiseOffence;
    private javax.swing.JLabel PlaceLabelInRaiseOffence;
    private javax.swing.JButton RaiseBtnInRaiseOffence;
    private javax.swing.JPanel RaiseOffencePanel;
    private javax.swing.JPanel RaiseOffenceTab;
    private javax.swing.JTextField ReportedByFieldInRaiseOffence;
    private javax.swing.JLabel ReportedByLabelInRaiseOffence;
    private javax.swing.JButton SearchBtnInClearOffence;
    private javax.swing.JButton SearchBtnInViewOffences;
    private javax.swing.JButton UploadBtnRaiseOffence;
    private javax.swing.JLabel VehNoViewOffencesLabel;
    private javax.swing.JTextField VehNumFielInViewOffence;
    private javax.swing.JTextField VehNumFieldInClearOffence;
    private javax.swing.JTextField VehNumFieldInRaiseOffence;
    private javax.swing.JLabel VehNumLableInClearOffence;
    private javax.swing.JLabel VehicleNumLableInRaiseOffence;
    private javax.swing.JPanel ViewOffencePanel;
    private javax.swing.JPanel ViewOffenceTab;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton SearchAllOffences;
    // End of variables declaration//GEN-END:variables
}
