/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tms.ui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import tms.business.AdminOperations;
import tms.business.impl.AdminOperationsImpl;

import tms.dao.RoleMasterDAO;

import tms.entities.UserMasterEO;
import tms.entities.RoleMasterEO;

import tms.factory.RoleMasterDAOFactory;

/**
 *
 * @author reddirani.battuluri
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        this.setVisible(true);
        initComponents();
        populateRoleNames();
    }
    
    private void populateRoleNames() {
        
           RoleMasterDAO roleMasterDAORef = RoleMasterDAOFactory.createRoleMasterDAO();
           List<RoleMasterEO> roleNames = roleMasterDAORef.findAllRoles();

           for (RoleMasterEO role : roleNames) {
               RoleNameCombo.addItem(role.getRoleName());
           }

       }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TMSTitle = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        UserNameField = new javax.swing.JTextField();
        PasswordLable = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        LoginBtn = new javax.swing.JButton();
        RoleNameLable = new javax.swing.JLabel();
        RoleNameCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1950, 1000));
        getContentPane().setLayout(null);

        TMSTitle.setBackground(new java.awt.Color(0, 0, 0));
        TMSTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        TMSTitle.setForeground(new java.awt.Color(204, 0, 0));
        TMSTitle.setText("  Traffic Management System");
        getContentPane().add(TMSTitle);
        TMSTitle.setBounds(490, 20, 740, 90);

        UserNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UserNameLabel.setText("Username");
        getContentPane().add(UserNameLabel);
        UserNameLabel.setBounds(820, 300, 110, 30);

        UserNameField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UserNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserNameField);
        UserNameField.setBounds(960, 300, 180, 40);

        PasswordLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PasswordLable.setText("Password");
        getContentPane().add(PasswordLable);
        PasswordLable.setBounds(820, 390, 110, 30);

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField);
        PasswordField.setBounds(960, 380, 180, 40);

        LoginBtn.setBackground(new java.awt.Color(102, 102, 255));
        LoginBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login");
        LoginBtn.setOpaque(false);
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn);
        LoginBtn.setBounds(920, 580, 100, 40);

        RoleNameLable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RoleNameLable.setText("Rolename");
        getContentPane().add(RoleNameLable);
        RoleNameLable.setBounds(820, 480, 100, 20);

        RoleNameCombo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
       // RoleNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "RTO", "Clerk", "Cop" }));
        
        
        RoleNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleNameComboActionPerformed(evt);
            }
        });
        getContentPane().add(RoleNameCombo);
        RoleNameCombo.setBounds(960, 470, 180, 40);
        

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tms/ui/cop.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 250, 350, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void UserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

                                   

    private void RoleNameComboActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             


    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String enteredUserName = UserNameField.getText();
        String enteredPassword = PasswordField.getText();
        String chooseRole = (String) RoleNameCombo.getSelectedItem();
        System.out.println(enteredUserName + " " + enteredPassword + " " + chooseRole);
        if (enteredUserName.isEmpty() || enteredPassword.isEmpty() || chooseRole.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter all the fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        RoleMasterEO role = new RoleMasterEO();
                role.setRoleName(chooseRole);
                UserMasterEO user = new UserMasterEO(enteredUserName,enteredPassword,role);
                AdminOperations admin = new AdminOperationsImpl();
                boolean loggedIn = admin.login(user);

        if (loggedIn) {
            this.dispose();
            
            switch(chooseRole) {
                case "Admin" : 
                    Admin adminFrame = new Admin();
                    adminFrame.setVisible(true);
                    break;
                case "RTO" : 
                    RTO rtoFrame = new RTO();
                    rtoFrame.setVisible(true);
                    break;
                case "Cop" : 
                    Cop copFrame = new Cop();
                    copFrame.setVisible(true);
                    break;
                case "Clerk" :
                    Clerk clerkFrame = new Clerk();
                    clerkFrame.setVisible(true);
                    break;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid credentials. Please try again.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }





    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLable;
    private javax.swing.JComboBox<String> RoleNameCombo;
    private javax.swing.JLabel RoleNameLable;
    private javax.swing.JLabel TMSTitle;
    private javax.swing.JTextField UserNameField;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}
